# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

# Main Page Setup

title: Abraham Galicia's Portfolio # This is what shows up in the tab of the browser



# Hero Section
name: Abraham Galicia
headline: Mechanical Engineer - Aerospace Concentration
description: >- # dont remove this line. this will ignore all new lines until the next section
  I’m Abraham Galicia, a Mechanical Engineering student at UC Berkeley, passionate about turning 
  ideas into functional, tested designs. I thrive at the intersection of CAD modeling, simulation 
  tools like ANSYS, and hands-on prototyping — from building autonomous seed-planting robots to analyzing 
  composite nozzles for high-heat environments. Whether collaborating on a research paper or machining 
  parts in the shop, I’m always looking for ways to learn, iterate, and make something better.

# Place your profile image in /assets/images/profile-image/folder and edit the file name
profile_image: assets/images/profile-image/photo_for_portfolio.jpg


# Link your resume
# You can place your resume in assets/resume/{resume file.pdf} or add external link such as pdf saved in google drive 
#resume-url: https://drive.google.com/file/d/13Z3duVzh-gguPU5r03oJVEE6rV9rd3DS/view?usp=sharing
resume-url: /assets/resume/Resume.pdf


# Set up external links - this will show up as small icons next to your name.

external-links:    # input only your own url slug. The icons with missing entries will not appear.
  linkedin: https://www.linkedin.com/in/abrahamg2025    # https://www.linkedin.com/in/{your url slug} 
  github: https://github.com/engineeringwabe    # https://github.com/{your url slug} 
  #stackoverflow:       # https://stackoverflow.com/users/{your url slug}
  #medium:            # https://medium.com/@{your url slug} 
  #twitter:   # https://x.com/{your url slug} 
  #threads:            # https://threads.net/@{your url slug} 
  #instragram:       # https://instagram.com/{your url slug} 
  #youtube:           # https://youtube.com/@{your url slug} 
  discord: https://discord.com/users/alex219819          # https://discord.com/users/{your url slug} 
  #bluesky:           # https://bsky.app/profile/{your url slug} 
  

# Skills Section - Add the list of your Skills by categories/tools. The indentation for each level needs to be precise. 
skills:
  - category: 3D Modeling
    tools:
    - Onshape
    - Solidworks
    - Fusion 360 (Autodesk)
  - category: Simulation & Analysis
    tools:
    - Finite Element Analysis (FEA)
    - ANSYS (Structural, Thermal)
    - Computational Fluid Dynamics (CFD)
    - MATLAB
  - category: Prototyping
    tools:
    - Laser Cutting
    - End Mill
    - Lathe
    - Drill press
    - 3D Printing
    - Water Jet Cutting
    - Arduino / Raspberry Pi
    - Breadboarding for circuit testing
  - category: Programming
    tools:
    - Python
    - C/C++
    - MATLAB
    - Eclipse
    - Visual Studio Code
    - Google Workspace
  


# Contact Form Setup. Setup an account and copy over the key. When someone fills out the form, it will be received in your email.
formspree-key:   https://formspree.io/f/xnndrrpb



# Active theme (Update this to switch themes). Make sure to keep the indentation the same.
colors:
  text: "#1b1f23"              # deep charcoal for strong readability
  border: "#e1e4e8"            # subtle gray for section separation
  link: "#007acc"              # confident blue used by VS Code and GitHub
  highlight: "#d73a49"         # vivid red for emphasis
  background: "#ffffff"        # clean white for strong contrast
  light_background: "#f6f8fa"  # soft blue-gray for section contrast

#########################################################################################################
# Build settings for the site. Editing the below may cause the site to malfunction.

collections:
  projects:
    output: true
    permalink: /projects/:path/


markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
      indent: 0

plugins:
  - jekyll-feed

include:
  - _projects


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
